# Generated by Django 4.2.6 on 2023-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categorias_productos_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='productos',
            name='origen',
            field=models.CharField(choices=[('NAC', 'NACIONAL'), ('IMP', 'IMPORTADO')], default='NAC', max_length=3),
        ),
    ]
